In [1]:
import numpy as np

In [2]:
arr= np.arange(0,13) # creating an array with the arange function in numpy

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
arr[3]

3

In [5]:
arr[3:6]

array([3, 4, 5])

In [6]:
arr[2]=90

In [7]:
arr[2]

90

In [8]:
arr[0:5]=100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12])

In [10]:
arr=np.arange(0,11)

In [11]:
slice_arr=arr[0:6]

In [12]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_arr[:]=99

In [14]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [15]:
arr 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arrCopy=arr.copy() # Will ccreate a copy of the original array and make no changes to the original array as it happened above

In [17]:
arr_2d=np.array([[5,10,15],[20,25,30],[40,45,50]])

In [18]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [40, 45, 50]])

In [19]:
arr_2d[1]

array([20, 25, 30])

In [20]:
arr_2d[1:3]

array([[20, 25, 30],
       [40, 45, 50]])

In [22]:
arr_2d[1][2]

30

In [27]:
slice_2d=arr_2d[:2,1:]

In [28]:
slice_2d

array([[10, 15],
       [25, 30]])

In [29]:
# Fancy indexing

In [33]:
arr2d=np.zeros((10,10)) # creating a 2D array

In [34]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [37]:
arr2d_length=arr2d.shape[1]

In [38]:
arr2d_length

10L

In [41]:
for i in range(arr2d_length):
    arr2d[i]=1

In [42]:
arr2d

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [45]:
for i in range(arr2d_length):
    arr2d[i]=i

In [46]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [49]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])