In [1]:
import numpy as np

In [2]:
arr=np.arange(50)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [6]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949,
        5.        ,  5.09901951,  5.19615242,  5.29150262,  5.38516481,
        5.47722558,  5.56776436,  5.65685425,  5.74456265,  5.83095189,
        5.91607978,  6.        ,  6.08276253,  6.164414  ,  6.244998  ,
        6.32455532,  6.40312424,  6.4807407 ,  6.55743852,  6.63324958,
        6.70820393,  6.78232998,  6.8556546 ,  6.92820323,  7.        ])

In [7]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
         1.62754791e+05,   4.42413392e+05,   1.20260428e+06,
         3.26901737e+06,   8.88611052e+06,   2.41549528e+07,
         6.56599691e+07,   1.78482301e+08,   4.85165195e+08,
         1.31881573e+09,   3.58491285e+09,   9.74480345e+09,
         2.64891221e+10,   7.20048993e+10,   1.95729609e+11,
         5.32048241e+11,   1.44625706e+12,   3.93133430e+12,
         1.06864746e+13,   2.90488497e+13,   7.89629602e+13,
         2.14643580e+14,   5.83461743e+14,   1.58601345e+15,
         4.31123155e+15,   1.17191424e+16,   3.18559318e+16,
         8.65934004e+16,   2.35385267e+17,   6.39843494e+17,
         1.73927494e+18,   4.72783947e+18,   1.28516001e+19,
         3.49342711e+19,   9.49611942e+19,   2.58131289e+20,
         7.01673591e+20,

In [8]:
#### Creating an array with random number & random normal distribution as given

In [9]:
A = np.random.randn(10)
A

array([-0.33421044, -0.95311974,  0.19369482, -0.33690746,  1.23014625,
       -0.23370885, -1.30383601,  1.01164977,  1.64816893,  0.39909569])

In [10]:
B= np.random.randn(10)
B

array([ 0.74060815, -0.22460765, -0.66663331,  0.26584108, -0.82681005,
       -0.39292447,  0.53078393,  0.09621302,  0.7157114 ,  0.64024327])

In [11]:
# Performing Binary Functions

In [12]:
A+B

array([ 0.40639771, -1.17772738, -0.47293849, -0.07106638,  0.4033362 ,
       -0.62663332, -0.77305208,  1.10786278,  2.36388034,  1.03933897])

In [13]:
# Finding max or min of two arrays
np.maximum(A,B)

array([ 0.74060815, -0.22460765,  0.19369482,  0.26584108,  1.23014625,
       -0.23370885,  0.53078393,  1.01164977,  1.64816893,  0.64024327])

In [14]:
# For the full documentation on Universal Array functions check out http://docs.scipy.org/doc/numpy-1.10.0/reference/ufuncs.html

In [15]:
# To call this webpage in this notebook we can code it like this
import webbrowser as wb
website='http://docs.scipy.org/doc/numpy-1.10.0/reference/ufuncs.html'
wb.open(website)

True